### ISSUE TITLE
hardhat Mainnet forking export error

### ISSUE THREAD

**Issue by jin10086** [Tenderly/hardhat-tenderly#3]
Unable to get transaction rerunning information: error processing transaction: user error: gas mismatch between receipt and actual gas used, message: Rerun gas mismatch for transaction 0xe4e8ab85135902fe29d29bbc36ca7e5fdbb30d092b6e8f65689e2c259c9cedeb. This can happen when the chain config is incorrect or the local node is not running the latest version.

Please check which hardfork is active on your local node. If you are not running the newest fork, comment out the forks block in tenderly.yaml.

**Comment by jin10086** [comment]
config 

```
  hardhat:
    chain_config:
      byzantium_block: 0
      constantinople_block: 0
      eip150_block: 0
      eip150_hash: "0x0000000000000000000000000000000000000000000000000000000000000000"
      eip155_block: 0
      eip158_block: 0
      homestead_block: 0
      istanbul_block: 0
      petersburg_block: 0
    forked_network: Mainnet
    project_slug: 
    protocol: ""
    rpc_address: 127.0.0.1:8545
```
